name: dxascalc
channels:
  - defaults
  - conda-forge 
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - scipy
  - pip:
    - pip
    - xraylib
    - dabax
    - pandas
    - matplotlib
    - ipywidgets
    - xraylib
    - xoppylib
    - dabax
